/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'milesd' at '08/10/15 23:32' with Gradle 2.2.1
 *
 * @author milesd, @date 08/10/15 23:32
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
